### ISSUE TITLE
Getting profile errors on multiple controls

### ISSUE THREAD

**Issue by smiller1032** [GoogleCloudPlatform/inspec-gcp-cis-benchmark#26]
When I run this profile against a GCP project, I get a significant number of profile errors on the controls. I want the controls to run but if it is not applicable in a project then each control should load into Heimdall as 'Not Applicable'.

**Comment by aaronlippold** [comment]
The key here would be to ensure that the `impact` is getting set to `0` to be displayed in Heimdall as Not Applicable.

For some of these controls, we may need to move to the `expect` syntax to ensure the right general impact is being set.

**Comment by KonradSchieban** [comment]
Hi @smiller1032 , can you please point to the exact controls which fail? We'd like to address this unwanted behavior if controls are failing but should be unapplicable. Are you getting control errors or exceptions?

**Comment by aaronlippold** [comment]
@smiller1032 can you let us know which controls are throwing errors or send us an example json result out of band. Thanks.

**Comment by rbclark** [comment]
I have run this scan against a completely fresh GCP account with nothing created in it and about half of the controls fail. The reason being that many of the tests do not account for parts of the environment being empty. Using [1.04-iam](https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/blob/master/controls/1.04-iam.rb) as an example, the code for that check is iterating over `service_account_cache.service_account_emails` however in my case it is completely empty since my account has no service account emails. The impact is set to medium but no tests were run since the array was empty, causing a profile error.

The following 41 controls all throw Profile Errors on a new account:

1. cis-gcp-1.4-iam
2. cis-gcp-1.7-iam
3. cis-gcp-3.6-networking
4. cis-gcp-3.7-networking
5. cis-gcp-3.8-networking
6. cis-gcp-3.9-networking
7. cis-gcp-4.1-vms
8. cis-gcp-4.2-vms
9. cis-gcp-4.3-vms
10. cis-gcp-4.4-vms
11. cis-gcp-4.5-vms
12. cis-gcp-4.6-vms
13. cis-gcp-4.7-vms
14. cis-gcp-4.8-vms
15. cis-gcp-5.1-storage
16. cis-gcp-5.2-storage
17. cis-gcp-6.1.2-db
18. cis-gcp-6.1.3-db
19. cis-gcp-6.2.1-db
20. cis-gcp-6.2.2-db
21. cis-gcp-6.2.3-db
22. cis-gcp-6.2.4-db
23. cis-gcp-6.2.5-db
24. cis-gcp-6.2.6-db
25. cis-gcp-6.2.7-db
26. cis-gcp-6.2.8-db
27. cis-gcp-6.2.9-db
28. cis-gcp-6.2.10-db
29. cis-gcp-6.2.11-db
30. cis-gcp-6.2.12-db
31. cis-gcp-6.2.13-db
32. cis-gcp-6.2.14-db
33. cis-gcp-6.2.15-db
34. cis-gcp-6.2.16-db
35. cis-gcp-6.3.1-db
36. cis-gcp-6.3.2-db
37. cis-gcp-6.3.3-db
38. cis-gcp-6.3.4-db
39. cis-gcp-6.3.5-db
40. cis-gcp-6.3.6-db
41. cis-gcp-6.3.7-db
